version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-service

  node-service:
    build:
      context: ./docker/api
      dockerfile: Dockerfile
    ports:
      - "3000"
      - "3001"
      - "3002"
      
    environment:
      DB_HOST: db
      DB_USERNAME: MarkysDatabase
      DB_PASSWORD: ThePassword
      DB_DATABASE: TheBestDatabase
    # Scale the service to have 3 instances
    scale: 3

  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: TheBestDatabase
      MYSQL_USER: MarkysDatabase
      MYSQL_PASSWORD: ThePassword
    volumes:     
      - ./docker/db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
